"""Add user fk to sets and workouts

Revision ID: 0af258395953
Revises: fe9b53d5880c
Create Date: 2022-07-11 20:53:19.671302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0af258395953"
down_revision = "fe9b53d5880c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sets", sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False)
    )
    op.create_foreign_key(None, "sets", "users", ["user_id"], ["id"])
    op.add_column(
        "workouts", sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False)
    )
    op.create_foreign_key(None, "workouts", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workouts", type_="foreignkey")
    op.drop_column("workouts", "user_id")
    op.drop_constraint(None, "sets", type_="foreignkey")
    op.drop_column("sets", "user_id")
    # ### end Alembic commands ###
