"""Update table Sets to make start_time nullable

Revision ID: 10eafeaba0d6
Revises: 6989712a0e3b
Create Date: 2023-02-12 17:14:41.492737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "10eafeaba0d6"
down_revision = "6989712a0e3b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sets", "start_time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sets", "start_time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
