"""Add notes field to workouts

Revision ID: 5e8ea23eb03f
Revises: 9cc569439b81
Create Date: 2022-07-16 19:54:10.716111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e8ea23eb03f"
down_revision = "9cc569439b81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "notes")
    # ### end Alembic commands ###
