"""Add owner_user_id to workout_types

Revision ID: 9883c28f3b21
Revises: 5e8ea23eb03f
Create Date: 2023-02-11 21:06:50.940482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9883c28f3b21"
down_revision = "5e8ea23eb03f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_types",
        sa.Column("owner_user_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, "workout_types", "users", ["owner_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_types", type_="foreignkey")
    op.drop_column("workout_types", "owner_user_id")
    # ### end Alembic commands ###
