name: CI

on: push

jobs:
  lint:
    name: Lint and Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.3.0"
      - name: Install Package and Dependencies
        run:
          poetry install
      - name: Lint
        run:
          poetry run make lint
      - name: Typecheck
        run:
          poetry run make typecheck
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: workout_api
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.3.0"
      - name: Install Package and Dependencies
        run: poetry install
      - name: Run Migrations
        run: poetry run alembic upgrade head
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost/workout_api"
      - name: Run DB Seeds
        run: poetry run bash db/run_seeds.sh
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost/workout_api"
      - name: Run DB Views
        run: poetry run bash db/run_views.sh
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost/workout_api"
      - name: Run Test
        env:
          API_JWT_SECRET: dummysecret
          DATABASE_URL: "postgresql://postgres:postgres@localhost/workout_api"
          STATIC_APPLICATION_KEY: lestibournes
        run:
          poetry run make test
